---
roles:
  split_pe_conf:
    provisioners:
      - type: pe_bootstrap
        answer_file: 'answer_files/pe.conf'

  #This pe.conf set the console host as the database_host as well
  #This installs postgres on the console node for use by console-services
  #while PuppetDB will use the pe-postgres node
  split_console_pe_conf:
    provisioners:
      - type: pe_bootstrap
        answer_file: 'answer_files/pe-console.conf'


  blank_resolve_conf:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"

  agent:
    provisioners:
      - type: pe_agent
        #version: '2016.4.2'
        master_vm: 'split-master'
